### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException of PowerArgs 

### ISSUE THREAD

**Issue by EbenZhang** [jasminsehic/PullRequestReleaseNotes#37]
Steps:
- Choco install the application
- run it

Get below exception

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PowerArgs, Version=3.6.0.0, Culture=neutral, PublicKeyToken=26a276264bbd55b8' or one of its dependencies. The system cannot find the file specified.
   at PullRequestReleaseNotes.Config.GetCommandLineInput(String[] args, ProgramArgs& programArgs)
   at PullRequestReleaseNotes.Program.ValidateConfiguration(String[] args) in C:\projects\unreleasedgithubhistory\src\PullRequestReleaseNotes\Program.cs:line 80
   at PullRequestReleaseNotes.Program.Main(String[] args) in C:\projects\unreleasedgithubhistory\src\PullRequestReleaseNotes\Program.cs:line 19
```

this happens since version v1.2.3. I guess missing 3rd party dlls in the nuget package. likely due to the change to dotnet core but just guessing.

**Comment by EbenZhang** [comment]
When I trying to find a working version, I got this with v1.2.2, not sure if it's fixed in latest version or not as latest has the above PowerArgs issue

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Net.ServicePointManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Net.ComNetOS' threw an exception. ---> System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section dllmap. (C:\ProgramData\chocolatey\lib\pullrequestreleasenotes\tools\PullRequestReleaseNotes.exe.Config line 18)
[22:01:50] at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
[22:01:50] at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
[22:01:50] at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
[22:01:50] at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
[22:01:50] --- End of inner exception stack trace ---
[22:01:50] at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
[22:01:50] at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
[22:01:50] at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
[22:01:50] at System.Configuration.ConfigurationManager.GetSection(String sectionName)
[22:01:50] at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
[22:01:50] at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
[22:01:50] at System.Diagnostics.DiagnosticsConfiguration.Initialize()
[22:01:50] at System.Diagnostics.DiagnosticsConfiguration.get_Sources()
[22:01:50] at System.Diagnostics.TraceSource.Initialize()
[22:01:50] at System.Net.Logging.InitializeLogging()
[22:01:50] at System.Net.Loggin...
```

**Comment by jasminsehic** [comment]
Thanks Eben, going to have a look at this on the weekend. I remember testing this on Mac, Linux and Windows so it should be working. Have you tried the `dotnet tool install` instead of Choco?

**Comment by jasminsehic** [comment]
Choco version is meant to have merged assemblies with Costura into the main executable, that looks to be broken. Will push a new version on weekend. You can use the `dotnet` version in meantime, that should work fine.
